---
# tasks file for roles/fase_2
- name: 1. Configurar WinRM con Task
  block:
    - name: 1.1 Crear directorio PS
      ansible.windows.win_file:
        path: "{{ fase_2_dir_whynotwin11 }}/PS"
        state: directory

    - name: 1.2 Validar existencia de Directorio PS
      ansible.windows.win_stat:
        path: "{{ fase_2_dir_whynotwin11 }}/PS"
      register: ps_dir_out

    - name: 1.3 Copiar PS a Directorio
      ansible.windows.win_copy:
        src: roles/fase_2/files/WinRM.ps1
        dest: "{{ fase_2_dir_whynotwin11 }}/PS/WinRM.ps1"
        remote_src: false
      when: ps_dir_out.stat.exists

- name: 2. Proceso de ISO para Windows 11
  block:
#    - name: Deshabilitar Windows Defender
#      ansible.windows.win_shell: |
#        Set-MpPreference -DisableRealtimeMonitoring $true
#      register: w_def

    - name: 2.1 Crear directorio ISO
      ansible.windows.win_file:
        path: "{{ fase_2_dir_whynotwin11 }}/ISO"
        state: directory

    - name: 2.2 Validar existencia de Directorio ISO
      ansible.windows.win_stat:
        path: "{{ fase_2_dir_whynotwin11 }}/ISO"
      register: iso_dir_out

    - name: 2.3 Copiar ISO a Directorio
      ansible.windows.win_copy:
        src: roles/fase_2/files/Win11_23H2_Spanish_Mexico_x64v2.iso
        dest: "{{ fase_2_dir_whynotwin11 }}/ISO/Win11_23H2_Spanish_Mexico_x64v2.iso"
        remote_src: false
      when: iso_dir_out.stat.exists

#        - name: 2.3 Descargar ISO de Windows 11
#          ansible.windows.win_get_url:
#            url: https://go.microsoft.com/fwlink/p/?LinkID=2206317&clcid=0x40a&culture=es-es&country=ES
#            dest: "{{ fase_2_dir_whynotwin11 }}/ISO/Win11_23H2_Spanish_Mexico_x64v2.iso"
#            timeout: 3600

    - name: 2.4 Montar ISO Windows 11 en {{ ansible_fqdn }}
      ansible.windows.win_shell: |
        Mount-DiskImage -ImagePath "{{ fase_2_dir_whynotwin11 }}/ISO/Win11_23H2_Spanish_Mexico_x64v2.iso"
      when: iso_dir_out.stat.exists

    - name: 2.5 Obtener la letra de la unidad donde se montó la ISO # CENA_X64FREE_ES-ES_DV9
      ansible.windows.win_shell: |
        Get-Volume -FileSystemLabel "CCCOMA_X64FRE_ES-MX_DV9" | Select-Object -ExpandProperty DriveLetter
      register: iso_mount
      args:
        executable: powershell.exe

    - name: 2.6 Mostrar letra de la unidad donde se montó la ISO
      ansible.builtin.debug:
        msg: "La ISO de Windows 11 se montó en la unidad: {{ iso_mount.stdout | trim }}"

- name: 3. Proceso de Upgrade por ISO
  block:
    - name: 3.1 Ejecutar el instalador de Windows 11 desde la ISO montada
      ansible.windows.win_shell: >
        Start-Process -FilePath "{{ iso_mount.stdout | trim }}:\setup.exe" -ArgumentList
        '/auto upgrade', '/quiet', '/eula accept', '/showoobe none', '/priority normal', '/noreboot',
        '/compat ignorewarning', '/migratedrivers all', '/copylogs C:\temp\ansible' -Wait
      args:
        executable: powershell.exe
      register: upd_w11

    - name: 3.2 Reiniciar el servidor para completar la instalación de Windows 11
      ansible.windows.win_reboot:
        msg: "El servidor se reiniciará para completar la instalación de Windows 11"
        reboot_timeout: 3600  # Ajuste a 1 hora para manejar reinicios prolongados
      when: upd_w11.rc == 0

    - name: 3.3 Realizar una Pausa
      ansible.builtin.pause:
        seconds: 30

    - name: 3.4 Reiniciar PC
      ansible.windows.win_reboot:

    - name: 3.5 Recoger Facts Windows 11
      ansible.builtin.setup:
      register: facts_w11

    - name: 3.6 Datos de Sistema Operativo W11
      ansible.builtin.debug:
        msg:
          - "Nombre de PC: {{ facts_w11.ansible_facts.ansible_hostname }}"
          - "Version SO: {{ facts_w11.ansible_facts.ansible_distribution }}"
          - "Arquitectura: {{ facts_w11.ansible_facts.ansible_architecture }}"

    - name: 3.7 Generar reporte de Actualizacion
      ansible.builtin.copy:
        content: |
          Reporte de Actualizacion para: {{ facts_w11.ansible_facts.ansible_hostname }}
          -----------------------------------------------
          - Version SO: {{ facts_w11.ansible_facts.ansible_distribution }}
          - Architecture: {{ facts_w11.ansible_facts.ansible_architecture }}
        dest: roles/fase_2/files/{{ ansible_fqdn }}-upgrade_report.txt
        mode: "0644"

    - name: 3.8 Instalar todas las actualizaciones pendientes en Windows 11
      ansible.windows.win_updates:
        category_names: "*"
        reboot: true
      register: update11_results_all
      retries: 3
      delay: 120
      until: update11_results_all.failed_update_count == 0
